In [1]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.2


In [ ]:
arr = np.array([1,2,3,4,5])
print(f"Original array: {arr}")

zeros = np.zeros(5)
print(f"Zeros: {zeros}")

rng = np.arange(0, 10) #start, stop, step(optional)
print(f"ARange: {rng}")

lin = np.linspace(0, 1, 5)
print(f"Linspace: {lin}")

Original array: [1 2 3 4 5]
Zeros: [0. 0. 0. 0. 0.]
ARange: [0 1 2 3 4 5 6 7 8 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [12]:
# ## Exercise 1.1: Create Arrays
evens = np.arange(2, 21, 2)
print(f"Evens: {evens}")

# 2. Create an array of 10 random integers between 1 and 50
rand_ints = np.random.randint(1, 51, 10)
print(f"Random ints: {rand_ints}")

Evens: [ 2  4  6  8 10 12 14 16 18 20]
Random ints: [48  5 11 34  6 39 44 16 15 12]


## Basic Array Properties 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(f"Array: {arr}")
print(f"Shape: {arr.shape}")      # Dimensions
print(f"Size: {arr.size}")        # Total elements
print(f"Dtype: {arr.dtype}")      # Data type
print(f"Ndim: {arr.ndim}")  

Array: [1 2 3 4 5 6]
Shape: (6,)
Size: 6
Dtype: int64
Ndim: 1


## Reshaping Arrays

In [14]:
arr = np.arange(1, 13)  # 1 to 12
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")

# Reshape to 2D
arr_2d = arr.reshape(3, 4)  # 3 rows, 4 columns
print(f"\nReshaped (3x4):\n{arr_2d}")

# Reshape to different shape
arr_2d_v2 = arr.reshape(4, 3)  # 4 rows, 3 columns
print(f"\nReshaped (4x3):\n{arr_2d_v2}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
