# NumPy - Hands-on

## Prerequisites
- Python basics (lists, loops)
- Importing modules

## Learning Objectives
By the end of this notebook, you will be able to:
- Create and manipulate NumPy arrays
- Perform element-wise operations
- Use indexing and slicing
- Apply statistical functions
- Work with 2D arrays

---

In [1]:
# Import NumPy
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.2


# Section 1: Creating Arrays

### 1.1 From Python List

In [2]:
# From a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 1.2 Using NumPy Functions

In [3]:
# Zeros
zeros = np.zeros(5)
print(f"Zeros: {zeros}")

# Ones
ones = np.ones(5)
print(f"Ones: {ones}")

# Range (like Python range)
rng = np.arange(0, 10, 2)  # start, stop, step
print(f"Arange: {rng}")

# Evenly spaced
lin = np.linspace(0, 1, 5)  # start, stop, num_points
print(f"Linspace: {lin}")

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


### 1.3 Random Arrays

In [4]:
# Random floats between 0 and 1
rand = np.random.rand(5)
print(f"Random floats: {rand}")

# Random integers
randint = np.random.randint(1, 100, 5)  # low, high, size
print(f"Random ints: {randint}")

# Set seed for reproducibility
np.random.seed(42)
print(f"With seed: {np.random.rand(3)}")

Random floats: [0.30075394 0.03437048 0.51517264 0.31632538 0.39563692]
Random ints: [ 6 58 43 94 79]
With seed: [0.37454012 0.95071431 0.73199394]


### Exercise 1.1: Create Arrays

**Problem:**
1. Create an array of even numbers from 2 to 20
2. Create an array of 10 random integers between 1 and 50

In [ ]:
# Solution
evens = np.arange(2, 21, 2)
print(f"Evens: {evens}")

random_ints = np.random.randint(1, 51, 10)
print(f"Random: {random_ints}")

# Section 2: Array Properties

### 2.1 Basic Properties

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(f"Array: {arr}")
print(f"Shape: {arr.shape}")      # Dimensions
print(f"Size: {arr.size}")        # Total elements
print(f"Dtype: {arr.dtype}")      # Data type
print(f"Ndim: {arr.ndim}")        # Number of dimensions

Array: [1 2 3 4 5 6]
Shape: (6,)
Size: 6
Dtype: int64
Ndim: 1


### 2.2 Reshaping Arrays

In [6]:
arr = np.arange(1, 13)  # 1 to 12
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")

# Reshape to 2D
arr_2d = arr.reshape(3, 4)  # 3 rows, 4 columns
print(f"\nReshaped (3x4):\n{arr_2d}")

# Reshape to different shape
arr_2d_v2 = arr.reshape(4, 3)  # 4 rows, 3 columns
print(f"\nReshaped (4x3):\n{arr_2d_v2}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 2.3 Flatten and Ravel

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{arr_2d}")

# Back to 1D
flat = arr_2d.flatten()
print(f"\nFlattened: {flat}")

2D array:
[[1 2 3]
 [4 5 6]]

Flattened: [1 2 3 4 5 6]


# Section 3: Indexing and Slicing

### 3.1 Basic Indexing (1D)

In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(f"Array: {arr}")
print(f"First: {arr[0]}")
print(f"Last: {arr[-1]}")
print(f"Slice [1:4]: {arr[1:4]}")
print(f"Every 2nd: {arr[::2]}")

Array: [10 20 30 40 50]
First: 10
Last: 50
Slice [1:4]: [20 30 40]
Every 2nd: [10 30 50]


### 3.2 Boolean Indexing (Filtering)

In [9]:
arr = np.array([10, 25, 30, 45, 50, 15])

# Create boolean mask
mask = arr > 25
print(f"Array: {arr}")
print(f"Mask (arr > 25): {mask}")

# Filter using mask
filtered = arr[mask]
print(f"Filtered: {filtered}")

# Shorthand
print(f"Shorthand: {arr[arr > 25]}")

Array: [10 25 30 45 50 15]
Mask (arr > 25): [False False  True  True  True False]
Filtered: [30 45 50]
Shorthand: [30 45 50]


### 3.3 Multiple Conditions

In [10]:
arr = np.array([5, 15, 25, 35, 45, 55])

# AND condition (use &)
result = arr[(arr > 10) & (arr < 40)]
print(f"Between 10 and 40: {result}")

# OR condition (use |)
result = arr[(arr < 10) | (arr > 50)]
print(f"Less than 10 or greater than 50: {result}")

Between 10 and 40: [15 25 35]
Less than 10 or greater than 50: [ 5 55]


# Section 4: Array Operations

### 4.1 Element-wise Operations

In [11]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Original: {arr}")
print(f"Add 10: {arr + 10}")
print(f"Multiply 2: {arr * 2}")
print(f"Square: {arr ** 2}")
print(f"Divide 2: {arr / 2}")

Original: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]
Divide 2: [0.5 1.  1.5 2.  2.5]


### 4.2 Array with Array

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a: {a}")
print(f"b: {b}")
print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"b / a: {b / a}")

a: [1 2 3 4]
b: [10 20 30 40]
a + b: [11 22 33 44]
a * b: [ 10  40  90 160]
b / a: [10. 10. 10. 10.]


### 4.3 Math Functions

In [13]:
arr = np.array([1, 4, 9, 16, 25])

print(f"Original: {arr}")
print(f"Square root: {np.sqrt(arr)}")
print(f"Log: {np.log(arr)}")
print(f"Exponential: {np.exp([1, 2, 3])}")

Original: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Exponential: [ 2.71828183  7.3890561  20.08553692]


### 4.4 Comparison: NumPy vs List

In [14]:
# With list - need a loop
my_list = [1, 2, 3, 4, 5]
squared_list = [x**2 for x in my_list]
print(f"List squared: {squared_list}")

# With NumPy - direct operation
my_array = np.array([1, 2, 3, 4, 5])
squared_array = my_array ** 2
print(f"Array squared: {squared_array}")

List squared: [1, 4, 9, 16, 25]
Array squared: [ 1  4  9 16 25]


# Section 5: Statistical Functions

### 5.1 Basic Statistics

In [15]:
arr = np.array([12, 15, 18, 22, 25, 28, 30, 35])

print(f"Array: {arr}")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Std Dev: {np.std(arr):.2f}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")

Array: [12 15 18 22 25 28 30 35]
Sum: 185
Mean: 23.125
Median: 23.5
Std Dev: 7.36
Min: 12
Max: 35


### 5.2 Index of Min/Max

In [16]:
arr = np.array([30, 10, 50, 20, 40])

print(f"Array: {arr}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")
print(f"Min value: {arr[np.argmin(arr)]}")

Array: [30 10 50 20 40]
Index of min: 1
Index of max: 2
Min value: 10


### 5.3 Sorting

In [17]:
arr = np.array([30, 10, 50, 20, 40])

print(f"Original: {arr}")
print(f"Sorted: {np.sort(arr)}")
print(f"Descending: {np.sort(arr)[::-1]}")

Original: [30 10 50 20 40]
Sorted: [10 20 30 40 50]
Descending: [50 40 30 20 10]


# Section 6: 2D Arrays

### 6.1 Creating 2D Arrays

In [18]:
# From nested list
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d)
print(f"Shape: {arr_2d.shape}")  # (rows, columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [19]:
# Using functions
zeros = np.zeros((2, 3))  # 2 rows, 3 columns
print(f"Zeros:\n{zeros}")

ones = np.ones((3, 2))
print(f"\nOnes:\n{ones}")

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### 6.2 Indexing 2D Arrays

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(f"Array:\n{arr}\n")

# Single element: arr[row, col]
print(f"Element [0,1]: {arr[0, 1]}")
print(f"Element [2,2]: {arr[2, 2]}")

# Entire row
print(f"Row 0: {arr[0]}")
print(f"Row 1: {arr[1]}")

# Entire column
print(f"Column 0: {arr[:, 0]}")
print(f"Column 2: {arr[:, 2]}")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element [0,1]: 2
Element [2,2]: 9
Row 0: [1 2 3]
Row 1: [4 5 6]
Column 0: [1 4 7]
Column 2: [3 6 9]


### 6.3 Slicing 2D Arrays

In [21]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"Array:\n{arr}\n")

# First 2 rows, first 2 columns
print(f"Top-left 2x2:\n{arr[:2, :2]}\n")

# Last 2 rows, last 2 columns
print(f"Bottom-right 2x2:\n{arr[1:, 2:]}")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Top-left 2x2:
[[1 2]
 [5 6]]

Bottom-right 2x2:
[[ 7  8]
 [11 12]]


### 6.4 Statistics on 2D (axis)

In [22]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(f"Array:\n{arr}\n")

# Sum all elements
print(f"Total sum: {np.sum(arr)}")

# Sum along axis
print(f"Sum per column (axis=0): {np.sum(arr, axis=0)}")
print(f"Sum per row (axis=1): {np.sum(arr, axis=1)}")

# Mean along axis
print(f"Mean per column: {np.mean(arr, axis=0)}")
print(f"Mean per row: {np.mean(arr, axis=1)}")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Total sum: 45
Sum per column (axis=0): [12 15 18]
Sum per row (axis=1): [ 6 15 24]
Mean per column: [4. 5. 6.]
Mean per row: [2. 5. 8.]


---

## Key Takeaways

**Import:**
```python
import numpy as np
```

**Create Arrays:**
```python
np.array([1,2,3])    # From list
np.zeros(5)          # All zeros
np.arange(0, 10)     # Range
np.random.rand(5)    # Random
```

**Operations:** Element-wise with `+`, `-`, `*`, `/`, `**`

**Statistics:** `np.mean()`, `np.sum()`, `np.max()`, `np.min()`, `np.std()`

**Indexing:**
```python
arr[0]           # First element
arr[arr > 5]     # Filter
arr_2d[0, 1]     # Row 0, Column 1
arr_2d[:, 0]     # All rows, Column 0
```

**Axis:** `axis=0` (columns), `axis=1` (rows)

---

## Additional Resources

- [NumPy Documentation](https://numpy.org/doc/stable/)
- [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)